<?php
use panix\engine\Html;


$icons = [
    'Социал' => [
        ['name' => 'icon-vk'],
        ['name' => 'icon-dropbox'],
        ['name' => 'icon-facebook'],
        ['name' => 'icon-google-plus'],
        ['name' => 'icon-instagram'],
        ['name' => 'icon-youtube'],
        ['name' => 'icon-youtube-play'],
        ['name' => 'icon-whatsapp'],
        ['name' => 'icon-viber'],
        ['name' => 'icon-whatsapp-2'],
        ['name' => 'icon-telegram-outline'],
        ['name' => 'icon-google-disk'],
        ['name' => 'icon-telegram'],
        ['name' => 'icon-twitter'],
        ['name' => 'icon-skype'],
    ],
    'Браузер & OS' => [
        ['name' => 'icon-windows'],
        ['name' => 'icon-windows-7'],
        ['name' => 'icon-netscape'],
        ['name' => 'icon-chrome'],
        ['name' => 'icon-firefox'],
        ['name' => 'icon-ie'],
        ['name' => 'icon-opera'],
        ['name' => 'icon-safari'],
        ['name' => 'icon-linux'],
        ['name' => 'icon-android'],
    ],
    'Файлы' => [
        ['name' => 'icon-file-app'],
        ['name' => 'icon-file-css'],
        ['name' => 'icon-file-doc'],
        ['name' => 'icon-file-zip'],
        ['name' => 'icon-file-xml'],
        ['name' => 'icon-file-sql'],
        ['name' => 'icon-file-gif'],
        ['name' => 'icon-file-html'],
        ['name' => 'icon-file-java'],
        ['name' => 'icon-file-key'],
        ['name' => 'icon-file-jpg'],
        ['name' => 'icon-file-php'],
        ['name' => 'icon-file-png'],
        ['name' => 'icon-file-psd'],
        ['name' => 'icon-file-rar'],
        ['name' => 'icon-file-txt'],
        ['name' => 'icon-file-pdf'],
    ],
    'Деньги' => [
        ['name' => 'icon-privat24'],
        ['name' => 'icon-webmoney'],
        ['name' => 'icon-paypal'],
        ['name' => 'icon-mastercard'],
        ['name' => 'icon-visa'],
        ['name' => 'icon-bank'],
        ['name' => 'icon-cash-money'],
        ['name' => 'icon-creditcard'],
        ['name' => 'icon-price-house'],
        ['name' => 'icon-currencies'],
    ],
    'Бизнес' => [
        ['name' => 'icon-copyright'],
        ['name' => 'icon-1c'],
        ['name' => 'icon-contract'],
        ['name' => 'icon-partner'],
        ['name' => 'icon-contract-hand'],
        ['name' => 'icon-operator'],
        ['name' => 'icon-monitor-stats'],
        ['name' => 'icon-stats'],
        ['name' => 'icon-supplier'],
        ['name' => 'icon-discount'],
    ],
    'Логотипы брендов' => [
        ['name' => 'icon-logo-icon'],
        ['name' => 'icon-logo'],
        ['name' => 'icon-logo-bold'],
        ['name' => 'icon-novaposhta'],
        ['name' => 'icon-lifecell'],
        ['name' => 'icon-vodafone'],
        ['name' => 'icon-kyivstar'],
        ['name' => 'icon-apple'],
        ['name' => 'icon-yandex'],
    ],
    'Стрелки' => [
        ['name' => 'icon-arrow-left'],
        ['name' => 'icon-arrow-right'],
        ['name' => 'icon-arrow-up'],
        ['name' => 'icon-arrow-down'],
        ['name' => 'icon-arrow-first'],
        ['name' => 'icon-arrow-last'],
        ['name' => 'icon-double-arrow-right'],
        ['name' => 'icon-double-arrow-left'],
        ['name' => 'icon-reload'],
        ['name' => 'icon-refresh'],
        ['name' => 'icon-move'],
        ['name' => 'icon-resize'],
        ['name' => 'icon-return-back'],
        ['name' => 'icon-sort'],
        ['name' => 'icon-reply'],
    ],
    'Разное' => [
        ['name' => 'icon-user'],
        ['name' => 'icon-menu'],
        ['name' => 'icon-config'],
        ['name' => 'icon-settings'],
        ['name' => 'icon-tools'],
        ['name' => 'icon-heart'],
        ['name' => 'icon-heart-fill'],
        ['name' => 'icon-eye'],
        ['name' => 'icon-eye-close'],
        ['name' => 'icon-phone'],
        ['name' => 'icon-location'],
        ['name' => 'icon-compare'],
        ['name' => 'icon-users'],
        ['name' => 'icon-delivery'],
        ['name' => 'icon-security'],
        ['name' => 'icon-folder-open'],
        ['name' => 'icon-language'],
        ['name' => 'icon-key'],
        ['name' => 'icon-home'],
        ['name' => 'icon-edit'],
        ['name' => 'icon-delete'],
        ['name' => 'icon-trashcan'],
        ['name' => 'icon-comments'],
        ['name' => 'icon-add'],
        ['name' => 'icon-locked'],
        ['name' => 'icon-cart'],
        ['name' => 'icon-shopcart'],
        ['name' => 'icon-database'],
        ['name' => 'icon-earth'],
        ['name' => 'icon-location-marker'],
        ['name' => 'icon-puzzle'],
        ['name' => 'icon-warning'],
        ['name' => 'icon-info'],
        ['name' => 'icon-check'],
        ['name' => 'icon-envelope'],
        ['name' => 'icon-filter'],
        ['name' => 'icon-image'],
        ['name' => 'icon-images'],
        ['name' => 'icon-sendmail'],
        ['name' => 'icon-download'],
        ['name' => 'icon-upload'],
        ['name' => 'icon-blocks'],
        ['name' => 'icon-template'],
        ['name' => 'icon-search'],
        ['name' => 'icon-sitemap'],
        ['name' => 'icon-newspaper'],
        ['name' => 'icon-location-map'],
        ['name' => 'icon-location-route'],
        ['name' => 'icon-seo-monitor'],
        ['name' => 'icon-copy'],
        ['name' => 'icon-books'],
        ['name' => 'icon-chip'],
        ['name' => 'icon-print'],
        ['name' => 'icon-save'],
        ['name' => 'icon-t'],
        ['name' => 'icon-sms'],
        ['name' => 'icon-history'],
        ['name' => 'icon-file-csv'],
        ['name' => 'icon-messages'],
        ['name' => 'icon-question'],
        ['name' => 'icon-grid'],
        ['name' => 'icon-table'],
        ['name' => 'icon-table-edit'],
        ['name' => 'icon-share'],
        ['name' => 'icon-time'],
        ['name' => 'icon-ip'],
        ['name' => 'icon-http'],
        ['name' => 'icon-calendar'],
        ['name' => 'icon-external-link'],
        ['name' => 'icon-laptop'],
        ['name' => 'icon-ban'],
        ['name' => 'icon-bug'],
        ['name' => 'icon-camera-movie'],
        ['name' => 'icon-camera-photo'],
        ['name' => 'icon-rename'],
        ['name' => 'icon-star'],
        ['name' => 'icon-speed'],
        ['name' => 'icon-speedometer'],
        ['name' => 'icon-energy'],
        ['name' => 'icon-chronometer'],
        ['name' => 'icon-log'],
        ['name' => 'icon-notification'],
        ['name' => 'icon-rss'],
        ['name' => 'icon-blocked'],
        ['name' => 'icon-loader'],
        ['name' => 'icon-smile'],
        ['name' => 'icon-calculator'],
        ['name' => 'icon-water166'],
        ['name' => 'icon-water167'],
        ['name' => 'icon-sliders'],
        ['name' => 'icon-megaphone'],
        ['name' => 'icon-hand-up'],
        ['name' => 'icon-hand-down'],
        ['name' => 'icon-tag'],
    ],


]
?>
<div class="row">
    <?php foreach ($icons as $gn => $group) { ?>
        <div class="col-sm-12 pt-3"><h3 class="text-center"><?= $gn; ?></h3></div>
        <?php foreach ($group as $icon) { ?>
            <div class="col-sm-2">
                <div class="card2 pb-3 text-center">
                    <i class="<?= $icon['name']; ?> icon-x2"></i>
                    <div><code><?= htmlspecialchars('<i class="' . $icon['name'] . '"></i>'); ?></code></div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
</div>



